### ISSUE TITLE
安装之后，任务栏图标不正常

### ISSUE THREAD

**Issue by yidane** [dawndiy/electronic-wechat-snap#2]
![wechat](https://user-images.githubusercontent.com/6446481/40970832-58161482-68ee-11e8-9e3b-cf505ac756b8.png)
请问该怎么处理呢？

**Comment by dawndiy** [comment]
这个是 Snap 在 Unity7 上 AppIndicator 的 BUG 。Gnome 上没有此问题。恐怕官方可能不会修复了，因为已经放弃 Unity 了

**Comment by yidane** [comment]
3ks，之前是自己编译没问题。看来还是从https://github.com/geeeeeeeeek/electronic-wechat/按照教程编译吧。

**Comment by dawndiy** [comment]
原版是正常的 electron 打包，是没问题的。这里的是 Snap 打包，在 Unity 下有这个问题，Gnome 上是正常的。

**Comment by yidane** [comment]
@dawndiy  ok，明白原因了。多谢多谢。
